Repository Bist07/EquiFood-App-A, pull requests merged in 2023-01, with the labels that each got.

#135 January Rough Plan for Gantt Chart
  January Rough Plan
Labels: documentation

#158 Added INSERT statements for Example Restaurants
  DDL/DDL for Restaurant.sql
Labels: task

#175 Implemented basic Order Received page.
  EquiFood-A-ReactNative/StackNavigator.js
  EquiFood-A-ReactNative/components/TimePicker.js
  EquiFood-A-ReactNative/components/ViewCart.js
  EquiFood-A-ReactNative/package-lock.json
  EquiFood-A-ReactNative/package.json
  EquiFood-A-ReactNative/screens/OrderPage.js
Labels: task

#195 Fixed Primary key and removed auto Increment
  DDL/DDL for RestaurantAdmin.sql
Labels: task

#198 createRestaurant test function
  EquiFood-A-ReactNative/data/createRestaurant.js
Labels: chore

#199 Test function for addition of items
  EquiFood-A-ReactNative/data/addItem.js
Labels: chore
